ALTER TABLE `licenses` CHANGE `updated_date` `modified` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `licenses` CHANGE `created_date` `created` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `licenses` CHANGE `deleted_flag` `del_flag` TINYINT(1) NULL DEFAULT '0';
ALTER TABLE `licenses` CHANGE `deleted_date` `del_date` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `monitoring_logs` CHANGE `deleted_date` `del_date` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `monitoring_logs` CHANGE `created_date` `created` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `monitoring_logs` CHANGE `deleted_flag` `del_flag` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `organizations` CHANGE `updated_date` `modified` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `organizations` CHANGE `deleted_date` `del_date` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `organizations` CHANGE `deleted_flag` `del_flag` INT(1) NOT NULL DEFAULT '0';
ALTER TABLE `organizations` CHANGE `created_date` `created` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `units` CHANGE `deleted_date` `del_date` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `units` CHANGE `updated_date` `modified` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `units` CHANGE `deleted_flag` `del_flag` INT(1) NOT NULL DEFAULT '0';
ALTER TABLE `units` CHANGE `created_date` `created` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `created_date` `created` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `updated_date` `modified` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `deleted_flag` `del_flag` INT(1) NOT NULL DEFAULT '0';
ALTER TABLE `users` CHANGE `deleted_date` `del_date` TIMESTAMP NULL DEFAULT NULL;